### PR TITLE
added feature to specify additional listen addresses then localhost

### PR DESCRIPTION
**Pull request by patrickpierson**
I tested this on my machine after making the changes by installing via: 
`$ python setup.py install`

I then ran: 
`$ httpony` 

Which setup the server on localhost as expected.  I then reran with: 
`$ httpony -l 0.0.0.0` 

Which ran the server on all addresses my system could listen on which is the expected new feature.  I updated the README.md and what I believe is the RTD documentation.  Let me know what you think.

### CODE REVIEW

**Comment by mblayman** [comment]
@patrickpierson Thanks for the contribution. There's lots of good stuff to work with here. I think we need to fix some thing up to make it a bit more pythonic. I see a couple of options:
1. If you want to learn some Python stuff, I can walk you through a bunch of changes that I think would help improve the code.
2. If you're not really interested in working on the branch a bunch, I can merge what you've got and fix it up myself.

Either way, some form of this code will eventually get merged. Let me know what you'd like to do.

**Comment by patrickpierson** [comment]
I am 100% for option one.  My python consists mostly of hacking together code and has no formal experience.  I fully expected you to kick it back to be honest.

**Comment by mblayman** [comment]
Cool! In that case, let's do this. :muscle: 

The first thing we need to do is to get your work on a different branch. The changes proposed are changes that come from your master branch. That's fine for one contribution, but it kind of messes up your environment if you want to do anything else in the future. The reason is that it causes your fork and my fork to diverge.

To get the work on a different branch, we can follow http://stackoverflow.com/questions/1628563/move-the-most-recent-commits-to-a-new-branch-with-git. For your case, I think it will look like:

```
git branch listen-flag
git reset --hard HEAD~2 # Because you made two commits to your master
# At this point a "git log" should show "bac7231..." as your last commit.
git checkout listen-flag
# "git log" should show the two commits that you made.
```

Now there are two things left to do: push the new branch to GitHub, forcibly update your master on GitHub to get back in sync with my fork's history.

```
# While on the listen-flag branch:
git push origin listen-flag
git checkout master
git push -f origin master
```

From the GitHub website, you should be able to propose the new `listen-flag` branch as a new PR. When I see the new PR on the different branch, we can close this PR and get hacking on the Python issues.

The next time we meet up, I can explain more about the branching stuff and why this is important. I can also walk you through what you could do in the future.

**Comment by patrickpierson** [comment]
yah I dont know why i didnt branch it myself in the first place.  Lets go ahead and close this.  I'll branch this feature tonight (I already have other changes that might be more pythonic as you were saying that I wanted to commit anyways).

**Pull request closed without merging**
